import { useState, useMemo } from 'react';

// This would typically come from an API
const mockGrubPacsData = [
  {
    id: 1,
    name: "BOX-2456",
    code: "#DL12345",
    location: "Room 202",
    floor: null,
    status: "HEALTHY",
    power: "ON",
    addedDate: "Today",
    ioniser: "ON",
    zone1Temp: "4°c",
    zone2Temp: "25°c",
    details: "normal",
    driver: true,
    vehicle: "DL1AD1234",
    percent: 50,
    added: "Today",
    locked: true,
    hasS: false,
    disconnected: false,
  },
  {
    id: 2,
    name: "BOX-2456",
    code: "#DL12345",
    location: "Room 202",
    floor: "Ground floor",
    status: "ERROR",
    power: "ON",
    addedDate: "Today",
    ioniser: "ON",
    zone1Temp: "4°c",
    zone2Temp: "25°c",
    details: "normal",
    driver: false,
    vehicle: "-",
    percent: 75,
    added: "Today",
    locked: false,
    hasS: false,
    disconnected: true,
  },
  {
    id: 3,
    name: "BOX-2456",
    code: "#DL12345",
    location: "Room 202",
    floor: null,
    status: "HEALTHY",
    power: "ON",
    addedDate: "Today",
    ioniser: "ON",
    zone1Temp: "4°c",
    zone2Temp: "25°c",
    details: "normal",
    driver: true,
    vehicle: "DL1AD1234",
    status: "CONNECTED",
    percent: 50,
    added: "Today",
    locked: false,
    hasS: false,
    disconnected: false,
  },
  {
    id: 4,
    name: "BOX-2456",
    code: "#DL12345",
    location: "Room 202",
    floor: null,
    status: "WARNING",
    power: "ON",
    addedDate: "Today",
    ioniser: "ON",
    zone1Temp: "4°c",
    zone2Temp: "25°c",
    details: "normal",
    vehicle: "-",
    percent: null,
    added: "Today",
    locked: true,
    hasS: false,
    disconnected: false,
  },
  {
    id: 5,
    name: "BOX-2456",
    code: "#DL12345",
    location: "Room 202",
    floor: null,
    status: "HEALTHY",
    power: "ON",
    addedDate: "Today",
    ioniser: "ON",
    zone1Temp: "4°c",
    zone2Temp: "25°c",
    details: "normal",
    vehicle: "-",
    percent: 75,
    added: "Today",
    locked: false,
    hasS: false,
    disconnected: true,
  },
  {
    id: 6,
    name: "BOX-2456",
    code: "#DL12345",
    location: "Room 202",
    floor: null,
    status: "HEALTHY",
    power: "ON",
    addedDate: "Today",
    ioniser: "ON",
    zone1Temp: "4°c",
    zone2Temp: "25°c",
    details: "normal",
    vehicle: "-",
    percent: 75,
    added: "Today",
    locked: false,
    hasS: true,
    disconnected: true,
  },
  // Powered off devices for testing
  {
    id: 7,
    name: "BOX-2456",
    code: "#DL12345",
    location: "Room 202",
    floor: null,
    status: "OFF",
    power: "OFF",
    addedDate: "Today",
    ioniser: "OFF",
    zone1Temp: "-",
    zone2Temp: "-",
    details: "OFFLINE",
    vehicle: "-",
    percent: 0,
    added: "Today",
    locked: false,
    hasS: false,
    disconnected: true,
  },
  {
    id: 8,
    name: "BOX-2456",
    code: "#DL12345",
    location: "Room 202",
    floor: "Ground floor",
    status: "OFFLINE",
    power: "OFF",
    addedDate: "Today",
    ioniser: "OFF",
    zone1Temp: "-",
    zone2Temp: "-",
    details: "OFFLINE",
    vehicle: "-",
    percent: 0,
    added: "Today",
    locked: false,
    hasS: false,
    disconnected: true,
  },
  {
    id: 9,
    name: "BOX-2456",
    code: "#DL12345",
    location: "Room 202",
    floor: null,
    status: "DISCONNECTED",
    power: "OFF",
    addedDate: "Today",
    ioniser: "OFF",
    zone1Temp: "-",
    zone2Temp: "-",
    details: "OFFLINE",
    vehicle: "-",
    percent: 0,
    added: "Today",
    locked: false,
    hasS: false,
    disconnected: true,
  },
  {
    id: 10,
    name: "BOX-2456",
    code: "#DL12345",
    location: "Room 202",
    floor: "Ground floor",
    status: "OFF",
    power: "OFF",
    addedDate: "Today",
    ioniser: "OFF",
    zone1Temp: "-",
    zone2Temp: "-",
    details: "OFFLINE",
    vehicle: "-",
    percent: 0,
    added: "Today",
    locked: false,
    hasS: false,
    disconnected: true,
  },
];

export const useGrubPacsData = () => {
  const [data, setData] = useState(mockGrubPacsData);

  const groups = useMemo(() => [
    {
      name: "NAME OF THE RESTAURANT",
      items: data.slice(0, 3),
    },
    {
      name: "Unassigned",
      items: data.slice(3, 6),
      unassigned: true,
    },
    {
      name: "Powered Off Devices",
      items: data.slice(6, 10),
      poweredOff: true,
    },
  ], [data]);

  return {
    grubpacsData: data,
    groups,
    setGrubPacsData: setData,
  };
}; 