name: Development Build

on:
    push:
        branches:
            - main

jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Check required secrets
              run: |
                  if [ -z "${{ secrets.EC2_HOST }}" ] || \
                     [ -z "${{ secrets.EC2_SSH_KEY }}" ] || \
                     [ -z "${{ secrets.EC2_USER }}" ]; then
                      echo "One or more required secrets are empty or not set"
                      exit 1
                  fi

            - name: Setup SSH key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519

            - name: Add EC2 host to known_hosts
              run: |
                  ssh-keyscan -t ed25519 -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

            - name: Build & Deploy
              run: |
                  ssh -i ~/.ssh/id_ed25519 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
                    source ~/.zshrc
                    source ~/.bashrc
                    source ~/.profile
                    ls
                    cd admin_grubpac
                    git stash
                    git pull origin main
                    export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" && \
                    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && \
                    export BUN_INSTALL="$HOME/.bun" && \
                    export PATH="$BUN_INSTALL/bin:$PATH" && \
                    source ~/.bashrc && \
                    npm i && \
                    npm run build

            - name: Done
              run: |
                  echo "Build Done"
